### PR TITLE
Revert "refactor: update tokens changesets to use the testing framework engine (#19626)"

### PR DESCRIPTION
**Pull request by erikburt**
This reverts commit `aa86ac2a53d0e006a53f23e99bf114b450f46f94`.

Reverts change introduced in #19626 as it is causing build errors.

### Notes

Tried bumping to v0.53.0 of `chainlink-deployments-framework` but that is causing test errors (#19690).

This is failing builds on develop and in merge queue:

```
# github.com/smartcontractkit/chainlink/deployment/tokens/changesets [github.com/smartcontractkit/chainlink/deployment/tokens/changesets.test]
Error: tokens/changesets/deploy_evm_link_tokens_test.go:165:23: undefined: runtime.New
Error: tokens/changesets/deploy_evm_link_tokens_test.go:166:13: undefined: runtime.WithEnvOpts
Error: tokens/changesets/deploy_sol_link_tokens_test.go:166:23: undefined: runtime.New
Error: tokens/changesets/deploy_sol_link_tokens_test.go:167:13: undefined: runtime.WithEnvOpts
```

This was able to be merged because go didn't invalidate the build/test cache when it clearly should have:

https://github.com/smartcontractkit/chainlink/actions/runs/18140475190/job/51629843700#step:15:298
```
github.com/smartcontractkit/chainlink/deployment/tokens/changesets	(cached)
```

We have seen similar problems before, this is a rare occurrence. Sometimes this is because the files are the same size before and after the change.

### CODE REVIEW

**Review by jmank88 — APPROVED** [review]

**Comment by erikburt** [comment]
We can roll forward with #19680
